### ISSUE TITLE
Checkmark widgets do not draw

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#107]
I upgraded [from F-droid](https://f-droid.org/repository/browse/?fdfilter=notification&fdid=org.isoron.uhabits&fdpage=2) recently (so 1.4.1 → 1.5.1), and now checkmark widgets say “`Error drawing widget`” and do not respond to clicks.

**Comment by iSoron** [comment]
Thank you for reporting. Could you please also attach the log file generated from the settings screen (Settings / Generate bug report)? I have received one other report, with the following stack trace. I just want to confirm that your bug is the same.

```
ava.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.eraseColor(int)' on a null object reference
   at org.isoron.uhabits.views.RingView.onDraw(RingView.java:195)
   at android.view.View.draw(View.java:16194)
   at android.view.View.draw(View.java:16106)
   at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
   at android.view.View.draw(View.java:16197)
   at android.view.View.draw(View.java:16106)
   at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
   at android.view.View.buildDrawingCacheImpl(View.java:15485)
   at android.view.View.buildDrawingCache(View.java:15351)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.buildRemoteViews(BaseWidgetProvider.java:280)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.onPostExecute(BaseWidgetProvider.java:264)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.onPostExecute(BaseWidgetProvider.java:209)
   at android.os.AsyncTask.finish(AsyncTask.java:651)
   at android.os.AsyncTask.-wrap1(AsyncTask.java)
   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5443)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by aleksejrs** [comment]
I just tried to use that menu item.  Did it work?

**Comment by iSoron** [comment]
I have just released a new version of the app (1.5.2) which should correct this issue. Could you please try it out and tell me the results? It should be available on Google Play (for beta testers) in a few hours, and from F-Droid in a couple of days.

**Comment by stelariusinfinitek** [comment]
I experience the same problem in the latest version. I just sent you a bug report.

**Comment by iSoron** [comment]
Thank you. Just for the record, here is the stacktrace, from your log.

```
java.lang.IllegalArgumentException: width and height must be > 0
   at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
   at org.isoron.uhabits.views.RingView.reallocateCache(RingView.java:187)
   at org.isoron.uhabits.views.RingView.onDraw(RingView.java:199)
   at android.view.View.draw(View.java:15247)
   at android.view.View.draw(View.java:15156)
   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
   at android.view.View.draw(View.java:15250)
   at android.view.View.draw(View.java:15156)
   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
   at android.view.View.buildDrawingCacheImpl(View.java:14488)
   at android.view.View.buildDrawingCache(View.java:14355)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.buildRemoteViews(BaseWidgetProvider.java:280)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.onPostExecute(BaseWidgetProvider.java:264)
   at org.isoron.uhabits.widgets.BaseWidgetProvider$RenderWidgetTask.onPostExecute(BaseWidgetProvider.java:209)
   at android.os.AsyncTask.finish(AsyncTask.java:636)
   at android.os.AsyncTask.access$500(AsyncTask.java:177)
   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5294)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by iSoron** [comment]
Is everyone affected by this issue using Nova Launcher? Have you manually resized the checkmark widget, or are you using its default size? Could you try to make it vertically larger, and see what happens?

**Comment by stelariusinfinitek** [comment]
Same problem on Trebuchet (stock Cyanogenmod launcher).

**Comment by iSoron** [comment]
Thank you @stelariusinfinitek, I was able to reproduce all these issues. By the way, the checkmark widget is not even supposed to be resizable. Nova Launcher is not following the official specification.

**Comment by stelariusinfinitek** [comment]
I'm glad you could reproduce them. :) We are waiting for a fix. I just love Loop Habit Tracker, one of the best open source apps there is. Thank you for your work!

**Comment by iSoron** [comment]
Please try out the new version 1.5.3 when it becomes available to you and let me know if this issue is still there.

**Comment by stelariusinfinitek** [comment]
You fixed it! Thanks. :)

**Comment by aleksejrs** [comment]
Verified that it works in 1.5.3.  Thanks.
