### ISSUE TITLE
App crashing after trying to reimport .db file backup (after phone reinstall)

### ISSUE THREAD

**Issue by Julianoe** [iSoron/uhabits#1680]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

Title.
**I had an older backup and it worked**. But I can't reimport my recent backup which is a shame because the first backup was just a test when I started using the app.

## Steps to reproduce
1. Backed up the data with full export backup
2. Reinstall the phone
3. Tried to Reimport after reinstall
4. the app crashes

## System information
 - Phone: Blackview BV6000
 - Phone Operating System: Android 7
 - App version: 2.1.1

## Bug Report 

```
---------- BUG REPORT BEGINS ----------
--------- beginning of crash
04-02 01:07:26.343 32278 32278 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:07:26.343 32278 32278 E AndroidRuntime: Process: org.isoron.uhabits, PID: 32278
04-02 01:07:26.343 32278 32278 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.MainActivity}: android.os.NetworkOnMainThreadException
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:07:26.343 32278 32278 E AndroidRuntime: 	... 9 more
04-02 01:08:01.223 32568 32568 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:08:01.223 32568 32568 E AndroidRuntime: Process: org.isoron.uhabits, PID: 32568
04-02 01:08:01.223 32568 32568 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.activities.habits.list.ListHabitsActivity}: android.os.NetworkOnMainThreadException
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:08:01.223 32568 32568 E AndroidRuntime: 	... 9 more
04-02 01:09:52.162 32759 32759 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:09:52.162 32759 32759 E AndroidRuntime: Process: org.isoron.uhabits, PID: 32759
04-02 01:09:52.162 32759 32759 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.activities.habits.list.ListHabitsActivity}: android.os.NetworkOnMainThreadException
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:09:52.162 32759 32759 E AndroidRuntime: 	... 9 more
04-02 01:11:15.668   648   648 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:11:15.668   648   648 E AndroidRuntime: Process: org.isoron.uhabits, PID: 648
04-02 01:11:15.668   648   648 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.activities.habits.list.ListHabitsActivity}: android.os.NetworkOnMainThreadException
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:11:15.668   648   648 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:11:15.668   648   648 E AndroidRuntime: 	... 9 more
04-02 01:11:36.519   800   800 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:11:36.519   800   800 E AndroidRuntime: Process: org.isoron.uhabits, PID: 800
04-02 01:11:36.519   800   800 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.activities.habits.list.ListHabitsActivity}: android.os.NetworkOnMainThreadException
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:11:36.519   800   800 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:11:36.519   800   800 E AndroidRuntime: 	... 9 more
04-02 01:12:15.439   889   889 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:12:15.439   889   889 E AndroidRuntime: Process: org.isoron.uhabits, PID: 889
04-02 01:12:15.439   889   889 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.MainActivity}: android.os.NetworkOnMainThreadException
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-02 01:12:15.439   889   889 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-02 01:12:15.439   889   889 E AndroidRuntime: 	... 9 more
04-03 01:01:59.788 23982 23982 E AndroidRuntime: FATAL EXCEPTION: main
04-03 01:01:59.788 23982 23982 E AndroidRuntime: Process: org.isoron.uhabits, PID: 23982
04-03 01:01:59.788 23982 23982 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.MainActivity}: android.os.NetworkOnMainThreadException
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-03 01:01:59.788 23982 23982 E AndroidRuntime: 	... 9 more
04-03 01:04:08.027 24484 24484 E AndroidRuntime: FATAL EXCEPTION: main
04-03 01:04:08.027 24484 24484 E AndroidRuntime: Process: org.isoron.uhabits, PID: 24484
04-03 01:04:08.027 24484 24484 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=106, result=-1, data=Intent { dat=content://org.nextcloud.documents/document/c315ded6d9dd68039f13c20678919567/97 flg=0x43 }} to activity {org.isoron.uhabits/org.isoron.uhabits.activities.habits.list.ListHabitsActivity}: android.os.NetworkOnMainThreadException
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: Caused by: android.os.NetworkOnMainThreadException
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1693)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(ListHabitsScreen.kt:130)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(ListHabitsScreen.kt:121)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(ListHabitsActivity.kt:129)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6919)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
04-03 01:04:08.027 24484 24484 E AndroidRuntime: 	... 9 more

App Version Name: 2.1.1
App Version Code: 20101
OS Version: 3.18.35 (1491960514)
OS API Level: 24
Device: Blackview
Model (Product): BV6000 (Blackview)
Manufacturer: Blackview
Other tags: release-keys
Screen Width: 720
Screen Height: 1280
External storage state: mounted


---------- BUG REPORT ENDS ------------






```

**Comment by Julianoe** [comment]
Anyone else having app crashing when trying to reimport a db save? Some help would be welcome in a way or another :( 
at least to reimport the habits. I can merge the tracked data later

**Comment by iSoron** [comment]
Hi @Julianoe, it looks like you are trying to import the backup directly from NextCloud. Does it work if you first download the backup file to your phone?

**Comment by Julianoe** [comment]
Oh wow it worked! Weird because I synced those files locally first. Not sure I understand what went wrong. The app missing some permissions to the synced folder or something like that maybe?
Good to know anyway and thanks for taking the time to look into it.
