### ISSUE TITLE
App crashes when Customize notifications is clicked

### ISSUE THREAD

**Issue by ssssy1000** [iSoron/uhabits#1758]
## Pre-submission checklist
-  I am submitting a bug report, not a feature request.
-  I have searched for similar issues, but did not find any matches.

## Description
When I click the setting "Customize notifications", the app crashes

## Steps to reproduce
1. Go to settings
2. Scroll down
3. Click Customize notifications

## System information
 - Phone: Google Pixel 5
 - Phone Operating System: Android 7.1.1
 - App version: 2.2.0

## Screenshots
<img width="191" alt="1688885318405" src="https://github.com/iSoron/uhabits/assets/98003627/fb57292a-6431-4143-a8df-489a79accf3d">
<img width="189" alt="1688885345066" src="https://github.com/iSoron/uhabits/assets/98003627/eb567a56-6d6d-4739-b742-e508fec64975">

## Log
```
FATAL EXCEPTION: main
                            Process: org.isoron.uhabits, PID: 11967
                            java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
                             at org.isoron.uhabits.notifications.AndroidNotificationTray$Companion.createAndroidNotificationChannel(AndroidNotificationTray.kt:171)
                             at org.isoron.uhabits.activities.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:103)
                             at androidx.preference.Preference.performClick(Preference.java:1173)
                             at androidx.preference.Preference.performClick(Preference.java:1148)
                             at androidx.preference.Preference$1.onClick(Preference.java:172)
                             at android.view.View.performClick(View.java:5637)
                             at android.view.View$PerformClick.run(View.java:22429)
                             at android.os.Handler.handleCallback(Handler.java:751)
                             at android.os.Handler.dispatchMessage(Handler.java:95)
                             at android.os.Looper.loop(Looper.java:154)
                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                             at java.lang.reflect.Method.invoke(Native Method)
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                            Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/org.isoron.uhabits-1/base.apk"],nativeLibraryDirectories=[/data/app/org.isoron.uhabits-1/lib/x86, /system/lib, /vendor/lib]]
                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                             at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                             at org.isoron.uhabits.notifications.AndroidNotificationTray$Companion.createAndroidNotificationChannel(AndroidNotificationTray.kt:171) 
                             at org.isoron.uhabits.activities.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:103) 
                             at androidx.preference.Preference.performClick(Preference.java:1173) 
                             at androidx.preference.Preference.performClick(Preference.java:1148) 
                             at androidx.preference.Preference$1.onClick(Preference.java:172) 
                             at android.view.View.performClick(View.java:5637) 
                             at android.view.View$PerformClick.run(View.java:22429) 
                             at android.os.Handler.handleCallback(Handler.java:751) 
                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                             at android.os.Looper.loop(Looper.java:154) 
                             at android.app.ActivityThread.main(ActivityThread.java:6119) 
                             at java.lang.reflect.Method.invoke(Native Method) 
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by hiqua** [comment]
Can you double-check which version you're using? I don't see v2.2.0 as having been tagged in the repo.

**Comment by ssssy1000** [comment]
I checked that the app version is indeed 2.2.0, which I cloned from github on June 20 and compiled with Android Studio

**Comment by hiqua** [comment]
Given that you already built it yourself, can you check whether reverting https://github.com/iSoron/uhabits/commit/f70d33878cfadac1103235d42e7c4fe025e4aa87 fixes it?

**Comment by ssssy1000** [comment]
I have revert the code to f70d338, but the problem still exists. I found this crash using the Android emulator, could it be related to this?
The screen recordings that trigger this crash:


https://github.com/iSoron/uhabits/assets/98003627/22ab1c62-b33e-47ce-855e-3bc63769e55f


Habits in the Settings Notifications:
![Screenshot_20230710-145232](https://github.com/iSoron/uhabits/assets/98003627/d2018894-5892-467f-a79e-53cf5e726120)

**Comment by hiqua** [comment]
I hadn't seen the Android version you mentioned, so when I couldn't reproduce it on an up-to-date Pixel 5, I assumed it was because of the version. But now I guess this error has been around for some time, but is specific to Android 7.
