### ISSUE TITLE
Failed to export full backup

### ISSUE THREAD

**Issue by aleskunder** [iSoron/uhabits#1854]
## Description
I've changed my phone and was trying to export-import all the data, but couldn't load/transfer full backup: an error message "couldn't copy" appears when I'm trying to save/send the file via nearby share or Bluetooth.

## Steps to reproduce
1. Go to settings
2. Click on export full backup
3. Choose save on device
4. See error: couldn't copy 

## System information
 - Phone: redmi note 8t
 - Phone Operating System: Android 11 rkq1
 - App version: 2.1.3

**Comment by aleskunder** [comment]
![IMG_20231025_094125_627](https://github.com/iSoron/uhabits/assets/88088974/62083a92-8909-4d30-b90f-5e44d771899a)
![IMG_20231025_094135_034](https://github.com/iSoron/uhabits/assets/88088974/3e647ab9-8e86-454d-bc90-4bf424e0e088)

**Comment by aleskunder** [comment]
[Bug Report - Loop Habit Tracker.zip](https://github.com/iSoron/uhabits/files/13161761/Bug.Report.-.Loop.Habit.Tracker.zip)

**Comment by janKir** [comment]
I face the same issue on a Xiaomi Mi Note 10 with Android 11. No matter which app in the sharing dialog I select, the export always fails.

**Comment by matkoniecz** [comment]
The same on Redmi 9 with Android 11, CSV export is also affected.
I tried and failed to transfer with saving as file with file browser (preinstalled, the same as screenshots above), Amaze file browser, Whatsapp, Gmail, K-9 Mail and Signal.

One more reason to abandon Xiaomi I guess? Ironically happened during migrating away from that phone.
I hope that I will figure out a way to avoid data loss - is there any other way to transfer data? Or help with fixing this issue?

**Comment by matkoniecz** [comment]
on trying to share with Signal I see in logs:

```
2025-10-13 16:33:26.592 17142-17187 ActivityThread          org.thoughtcrime.securesms           E  Failed to find provider info for org.isoron.uhabits
2025-10-13 16:33:26.598 17142-17174 ShareViewModel          org.thoughtcrime.securesms           W  Could not load share data.
                                                                                                    java.io.FileNotFoundException: No content provider: content://org.isoron.uhabits/external-files/CSV/Loop%20Habits%20CSV%202025-10-13.zip
                                                                                                    	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1994)
                                                                                                    	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1823)
                                                                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1500)
                                                                                                    	at org.thoughtcrime.securesms.mms.PartAuthority.openExternalFileStream(PartAuthority.java:240)
                                                                                                    	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:88)
                                                                                                    	at org.thoughtcrime.securesms.util.MediaUtil.getMediaSize(MediaUtil.java:210)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository$Companion.getSize(ShareRepository.kt:153)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository$Companion.access$getSize(ShareRepository.kt:131)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository.resolve(ShareRepository.kt:41)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository.resolve$lambda$1(ShareRepository.kt:27)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository.$r8$lambda$kIbg86fIFMDr8TbdzFYf25CsvUY(ShareRepository.kt:0)
                                                                                                    	at org.thoughtcrime.securesms.sharing.v2.ShareRepository$$ExternalSyntheticLambda1.call(R8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
                                                                                                    	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
                                                                                                    	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:100)
2025-10-13 16:33:26.596 17142-17187 ActivityThread          org.thoughtcrime.securesms           E  Failed to find provider info for org.isoron.uhabits
```

**Comment by matkoniecz** [comment]
Earlier I see `2025-10-13 16:33:25.653  1144-2147  UriGrantsManagerService system_server                        W  For security reasons, the system cannot issue a Uri permission grant to content://org.isoron.uhabits/external-files/CSV/Loop%20Habits%20CSV%202025-10-13.zip [user 0]; use startActivityAsCaller() instead`
