### ISSUE TITLE
Import button fails, probably missing files permission

### ISSUE THREAD

**Issue by MarkJeronimus** [iSoron/uhabits#2013]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches. **Not a dup of #1680**

## Description
When I tap the Import option in Settings, the app crashes, repeatably. Phone suggested to clear cashes, which didn't help.

When I go to App info → Permissions, there's only a "Notifications" permission that can be allowed or denied (it's allowed). I expect to see a "Photos and videos" permission, in order to select a file to import, but it's not listed.

I installed Habits through F-Droid.

## System information
 - Phone: **Samsung S20 Plus**
 - Phone Operating System: **Android 13**
 - App version: **2.2.0**

## Screenshots
![Screenshot_20240626_225403_Permission controller](https://github.com/iSoron/uhabits/assets/5273753/a8208521-9d32-428b-87f4-256195c820f6)

**Comment by hiqua** [comment]
So far I haven't been able to reproduce on Android 14, 2.2.1.

In my case, the import dialog uses the file picker as it should, which also doesn't require file permissions. Might be specific to Android 14, need to try on Android 13.

**Comment by nanoinverno** [comment]
Hi,

I have a quite similar behaviour so I post my data here instead of opening a new bug-report :)

Right now, I am moving my system from a SM-G900F to a SM-G900F with a newer LineageOS-Version and importing the Full Backup throws the error `failed to import data`.

- Both App-Versions are `2.2.0`, so it should *not* be related to #211.
- Both installed via F-Droid.
- I did a `Repair database` before ex- and importing.
- I cannot give file-access-rights to the app, maybe there is something changed in the OS in terms of access.

<details>
<summary>Here is the log I saved directly after failed import.</summary>

```
---------- BUG REPORT BEGINS ----------
--------- beginning of main
10-18 14:51:58.483 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:00.199 17674 17694 W System  : A resource failed to call close. 
10-18 14:52:00.484 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:02.485 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:04.486 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:06.487 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:08.488 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:10.490 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:12.492 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:14.493 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:16.495 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:18.496 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:20.497 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:22.499 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:24.500 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:26.502 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:28.503 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:30.505 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:32.506 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:34.507 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:36.509 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:38.510 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:40.511 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:42.513 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:44.514 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:46.516 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:48.517 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:50.518 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:52.520 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:54.522 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:56.523 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:52:58.524 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:00.526 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:02.527 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:04.529 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:06.530 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:08.531 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:10.532 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:12.533 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:14.535 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:16.536 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:18.537 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:20.538 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:22.539 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:24.541 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:26.542 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:28.543 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:30.544 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:32.545 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:34.546 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:36.547 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:38.547 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:40.548 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:42.549 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:44.551 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:46.552 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:48.553 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:50.554 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:52.555 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:54.556 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:56.556 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:53:58.557 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:00.313 17674 17674 I MidnightTimer: Scheduling refresh for 32760687 ms from now
10-18 14:54:00.326 17674 17674 E FileUtils: getDir: all potential parents are null or non-writable
10-18 14:54:00.326 17674 17674 E ListHabitActivity: TaskRunner failed
10-18 14:54:00.326 17674 17674 E ListHabitActivity: java.lang.NullPointerException
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.database.AutoBackup.<init>(Unknown Source:21)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onResume(Unknown Source:90)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.Activity.performResume(Activity.java:8129)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.os.Looper.loop(Looper.java:223)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-18 14:54:00.326 17674 17674 E ListHabitActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-18 14:54:00.343 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:00.557 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:01.430 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:01.516 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:02.387 17674 17674 I MidnightTimer: Pausing timer
10-18 14:54:02.526 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:02.558 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:04.558 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:06.395 17674 17674 I MidnightTimer: Scheduling refresh for 32754605 ms from now
10-18 14:54:06.403 17674 17674 E FileUtils: getDir: all potential parents are null or non-writable
10-18 14:54:06.403 17674 17674 E ListHabitActivity: TaskRunner failed
10-18 14:54:06.403 17674 17674 E ListHabitActivity: java.lang.NullPointerException
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.database.AutoBackup.<init>(Unknown Source:21)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onResume(Unknown Source:90)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.Activity.performResume(Activity.java:8129)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.os.Looper.loop(Looper.java:223)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-18 14:54:06.403 17674 17674 E ListHabitActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-18 14:54:06.418 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:06.443 17674 17674 I MidnightTimer: Pausing timer
10-18 14:54:06.559 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:08.559 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:10.560 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:12.561 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:14.562 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:15.640 17674 17674 W System.err: java.io.IOException: No such file or directory
10-18 14:54:15.641 17674 17674 W System.err: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
10-18 14:54:15.641 17674 17674 W System.err: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
10-18 14:54:15.641 17674 17674 W System.err: 	at java.io.File.createTempFile(File.java:2018)
10-18 14:54:15.641 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onOpenDocumentResult(Unknown Source:37)
10-18 14:54:15.641 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(Unknown Source:13)
10-18 14:54:15.641 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(Unknown Source:7)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5006)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5054)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.os.Looper.loop(Looper.java:223)
10-18 14:54:15.641 17674 17674 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-18 14:54:15.641 17674 17674 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:54:15.641 17674 17674 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-18 14:54:15.642 17674 17674 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-18 14:54:15.646 17674 17674 I MidnightTimer: Scheduling refresh for 32745354 ms from now
10-18 14:54:15.651 17674 17674 E FileUtils: getDir: all potential parents are null or non-writable
10-18 14:54:15.651 17674 17674 E ListHabitActivity: TaskRunner failed
10-18 14:54:15.651 17674 17674 E ListHabitActivity: java.lang.NullPointerException
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.database.AutoBackup.<init>(Unknown Source:21)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onResume(Unknown Source:90)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.Activity.performResume(Activity.java:8129)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.os.Looper.loop(Looper.java:223)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-18 14:54:15.651 17674 17674 E ListHabitActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-18 14:54:15.667 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:16.563 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:18.564 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:20.565 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:22.567 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:23.474 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:23.562 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:24.568 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:24.722 17674 17674 I MidnightTimer: Pausing timer
10-18 14:54:24.839 17674 17708 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-18 14:54:26.568 17674 17690 E .isoron.uhabit: failed to connect to jdwp control socket: Connection refused
10-18 14:54:27.840 17674 17674 E FileUtils: getDir: all potential parents are null or non-writable
10-18 14:54:27.840 17674 17674 W System.err: java.io.IOException: log dir should not be null
10-18 14:54:27.840 17674 17674 W System.err: 	at org.isoron.uhabits.AndroidBugReporter.dumpBugReportToFile(Unknown Source:88)
10-18 14:54:27.840 17674 17674 W System.err: 	at org.isoron.uhabits.core.ui.screens.habits.list.ListHabitsBehavior.onSendBugReport(Unknown Source:2)
10-18 14:54:27.840 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onSettingsResult(Unknown Source:24)
10-18 14:54:27.840 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsScreen.onResult(Unknown Source:9)
10-18 14:54:27.840 17674 17674 W System.err: 	at org.isoron.uhabits.activities.habits.list.ListHabitsActivity.onActivityResult(Unknown Source:7)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5006)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5054)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-18 14:54:27.840 17674 17674 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-18 14:54:27.841 17674 17674 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:54:27.841 17674 17674 W System.err: 	at android.os.Looper.loop(Looper.java:223)
10-18 14:54:27.841 17674 17674 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-18 14:54:27.841 17674 17674 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:54:27.841 17674 17674 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-18 14:54:27.841 17674 17674 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

App Version Name: 2.2.0
App Version Code: 20200
OS Version: 3.4.113-g5650d2bb24c (ae82cfcde6)
OS API Level: 30
Device: klte
Model (Product): SM-G900F (klte)
Manufacturer: samsung
Other tags: release-keys
Screen Width: 1080
Screen Height: 1920
External storage state: mounted


---------- BUG REPORT ENDS ------------
```

</details>

Thanks for all your Work!

**Comment by AdityaMH** [comment]
I try to import and export. Both of them become force close.
