### ISSUE TITLE
Some Exception when testing the app

### ISSUE THREAD

**Issue by WangGuox1n** [iSoron/uhabits#505]
Hi, I developed an automatic-testing  tool and it detected these exceptions in your app(version 1.7.9).
I would like to know if you consider them as bug?

First exception:
**STACK_TRACE**= E/AndroidRuntime(25232): FATAL EXCEPTION: main
E/AndroidRuntime(25232): Process: org.isoron.uhabits, PID: 25232
E/AndroidRuntime(25232): java.lang.NullPointerException
E/AndroidRuntime(25232): 	at org.isoron.uhabits.activities.common.dialogs.WeekdayPickerDialog.onClick(WeekdayPickerDialog.java:46)
E/AndroidRuntime(25232): 	at android.support.v7.app.AlertController$AlertParams$4.onItemClick(AlertController.java:1080)
E/AndroidRuntime(25232): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(25232): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime(25232): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime(25232): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime(25232): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(25232): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(25232): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(25232): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(25232): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25232): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(25232): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(25232): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(25232): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by WangGuox1n** [comment]
Second Exception:

**STACK_TRACE**= E/AndroidRuntime(26302): FATAL EXCEPTION: main
E/AndroidRuntime(26302): Process: org.isoron.uhabits, PID: 26302
E/AndroidRuntime(26302): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=org.isoron.uhabits }
E/AndroidRuntime(26302): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
E/AndroidRuntime(26302): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime(26302): 	at android.app.Activity.startActivityForResult(Activity.java:3424)
E/AndroidRuntime(26302): 	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
E/AndroidRuntime(26302): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
E/AndroidRuntime(26302): 	at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime(26302): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
E/AndroidRuntime(26302): 	at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime(26302): 	at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime(26302): 	at org.isoron.uhabits.activities.about.AboutRootView.onClickRate(AboutRootView.java:108)
E/AndroidRuntime(26302): 	at org.isoron.uhabits.activities.about.AboutRootView$$ViewBinder$1.doClick(AboutRootView$$ViewBinder.java:26)
E/AndroidRuntime(26302): 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
E/AndroidRuntime(26302): 	at android.view.View.performClick(View.java:4438)
E/AndroidRuntime(26302): 	at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime(26302): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(26302): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26302): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(26302): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(26302): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26302): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(26302): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(26302): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(26302): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by WangGuox1n** [comment]
Third Exception:

**STACK_TRACE**= E/WindowManager(26406): android.view.WindowLeaked: Activity org.isoron.uhabits.activities.habits.list.ListHabitsActivity has leaked window android.widget.LinearLayout{52910060 V.E..... ......I. 0,0-264,96} that was originally added here
E/WindowManager(26406): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(26406): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(26406): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(26406): 	at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:85)
E/WindowManager(26406): 	at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:168)
E/WindowManager(26406): 	at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:116)
E/WindowManager(26406): 	at android.view.View.performLongClick(View.java:4474)
E/WindowManager(26406): 	at android.view.View$CheckForLongPress.run(View.java:18401)
E/WindowManager(26406): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager(26406): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager(26406): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(26406): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(26406): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(26406): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(26406): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(26406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(26406): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by hiqua** [comment]
Is there a way to reproduce this?

**Comment by anlalalu** [comment]
@hiqua All these issues are reproduced. See #534  #532  #533

**Comment by iSoron** [comment]
Thank you for the bug reports, @WangGuox1n. This seems like a useful tool. Let's move the discussion to their specific issues #534, #532 and #533.
