### ISSUE TITLE
window leak in ShowHabitActivity

### ISSUE THREAD

**Issue by anlalalu** [iSoron/uhabits#533]
###### Reproduction Steps

1. select a habit
2. long clickc 'more options'
3. press 'back' quickly

###### Stack Trace

E/WindowManager: android.view.WindowLeaked: Activity org.isoron.uhabits.activities.habits.show.ShowHabitActivity has leaked window android.widget.LinearLayout{5293e398 V.E..... ......I. 0,0-264,96} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:86)
                                                    at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:174)
                                                    at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:123)
                                                    at android.view.View.performLongClick(View.java:4474)
                                                    at android.view.View$CheckForLongPress.run(View.java:18401)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 1.7.11(dev)

Android Version = 4.4.4

**Comment by iSoron** [comment]
Thank you for the bug report, but I wouldn't consider this a significant issue.
