### ISSUE TITLE
crash when editing habit

### ISSUE THREAD

**Issue by anlalalu** [iSoron/uhabits#534]
###### Reproduction Steps

1. select a habit which enable reminder
2. tap 'edit'
3. tap 'Any day of the week' and the Select days dailog appears
4. uncheck all the days
5. rotate the screen
6. select a day

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.isoron.uhabits, PID: 3411
                                                 java.lang.NullPointerException
                                                     at org.isoron.uhabits.activities.common.dialogs.WeekdayPickerDialog.onClick(WeekdayPickerDialog.java:46)
                                                     at android.support.v7.app.AlertController$AlertParams$4.onItemClick(AlertController.java:1081)
                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:299)
                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
                                                     at android.widget.AbsListView$3.run(AbsListView.java:3645)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Screen Shot

![Screen Shot1](https://user-images.githubusercontent.com/46981872/71345551-a7e4b480-25a0-11ea-8356-f6f2edcc99fe.png)

![Screen Shot2](https://user-images.githubusercontent.com/46981872/71345571-b29f4980-25a0-11ea-84f3-000c5937e1fc.png)

###### Debug info
App Version = 1.7.11(dev)

Android Version = 4.4.4

**Comment by recheej** [comment]
I have a fix for this

**Comment by iSoron** [comment]
A fix for this issue was implemented in b9c9d68, and should be released with Loop 1.8.3. Thank you @anlalalu for reporting it, and @recheej for fixing it!
