### ISSUE TITLE
Crash when creating widgets on some devices

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#72]
Reported at the Google Play Developer console. User message:

> It's crashing for some reason. I tapped the widget a few times to change it, but it didn't

Stack trace:

<pre>
java.lang.RuntimeException: Unable to start receiver org.isoron.uhabits.widgets.CheckmarkWidgetProvider: java.lang.IllegalArgumentException: bitmap size exceeds 32bits
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2619)
	at android.app.ActivityThread.access$1700(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5341)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: bitmap size exceeds 32bits
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:819)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:777)
	at android.view.View.buildDrawingCache(View.java:13849)
	at org.isoron.uhabits.widgets.BaseWidgetProvider.updateWidget(BaseWidgetProvider.java:119)
	at org.isoron.uhabits.widgets.BaseWidgetProvider.onUpdate(BaseWidgetProvider.java:91)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2612)
	... 10 more
</pre>

Device: Lenovo TAB 2 A7-20F (Tab2A7-20F)
App version: 1.3.3

**Comment by iSoron** [comment]
Even though I own a Lenovo TAB 2 A10, I still cannot reproduce this issue. If anyone has better luck, please let me know.

**Comment by iSoron** [comment]
I am closing this issue, since I can't reproduce this bug and since it no longer causes a crash.
